### ISSUE TITLE
Fix Bonsai template compatibility w/ 0.17

### ISSUE THREAD

**Issue by carterbrett** [risc0/bonsai-foundry-template#46]
Reminder: Need to confirm with Jeremy that the intermediate fix is on verifier contract issue ([thread Slack](https://risc0.slack.com/archives/C03J8034W10/p1692050719755999)).

**Comment by capossele** [comment]
In order for the RiscZeroGroth16Verifier contract to be more agnostic to changes in the WIP repo such as changes that would affect the recursion predicates and/or changes to the RV32IM circuit, a possible solution would be to make the following values modifiable via some contract call.

https://github.com/risc0/risc0/blob/81578ba46f70b9f27152a3f36fa4d8994827bac9/bonsai/ethereum/contracts/groth16/RiscZeroGroth16Verifier.sol#L84-L86

Somewhat related to this issue is also https://github.com/risc0/risczero-wip/issues/282
